
; SPDX-FileName: frs_jr_random.mac
; SPDX-FileCopyrightText: Copyright 2023, Scott Giese
; SPDX-License-Identifier: GPL-3.0-or-later


randomByte      .macro
                lda RNG_DAT_LO
                and #$FF
                .endmacro

randomByteY     .macro
                ldy RNG_DAT_LO
                .endmacro

randomWord      .macro
                lda RNG_DAT_LO
                .endmacro

random          .macro clamp
                ; TODO:
                .endmacro
